Attendance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from accounts.views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/',auth_views.LoginView.as_view(template_name="registration/login.html"),name='login'),
    path('accounts/logout/',auth_views.LogoutView.as_view(template_name="registration/logout.html"),name='logout'),
  	path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
    path('home/', Home,name='home'),
]

student/urls.py
from django.urls import path
from .views import HomePageView,Profile,SubjectAttendance

app_name = 'student'


urlpatterns = [
	# path('', HomePageView,name='index'),
	path('profile/', Profile,name='profile'),
	path('attendance/',SubjectAttendance,name='attendance'),
	


]

teacher/urls.py
from django.urls import path
from .views import Profile,RandomCodeGenerator,Button,PanelListView

app_name = 'teacher'

urlpatterns = [
      # path('',HomePageView,name='index'),
      path('panels/', PanelListView,name='panel_list'),
      path('code/<panel_number>/', RandomCodeGenerator,name='requested'),
   ]

teacher/models.py
from django.db import models
from django.contrib.auth import get_user_model
from accounts.models import Subject,Panel


User=get_user_model()

class Teacher(models.Model):
    user              =models.OneToOneField(User,on_delete=models.CASCADE)
    panel             =models.ForeignKey(Panel,on_delete=models.CASCADE)
    first_name        =models.CharField(max_length=255,blank=True)
    last_name         =models.CharField(max_length=255,blank=True)
    subject           =models.ForeignKey(Subject,on_delete=models.CASCADE)

    
    def __str__(self):
        return str(self.user)

class SecretCode(models.Model):
    code               =models.IntegerField()
    teacher_username   =models.IntegerField(default=0,null=False,blank=False)
    date_time_created  =models.DateTimeField(auto_now_add=False)
    panel              =models.ForeignKey(Panel,on_delete=models.CASCADE)

teacher/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .models import Teacher
from django.urls import reverse
from django.http import HttpResponseRedirect
import random
import string
from accounts.models import Panel
from .models import SecretCode
from django.utils import timezone


User=get_user_model()

# @login_required
# def HomePageView(request):
#   return HttpResponseRedirect(reverse('teacher:pr'))
 
@login_required
def Profile(request):
    userid=request.user.id
    user=User.objects.get(id=userid)
    teacher=Teacher.objects.get(user=user)
    context={
    'erp':user.username,
    'name':(teacher.first_name+"\t"+teacher.last_name),
    'subject':teacher.subject,
        }

    return render(request,"teacher/profile.html",context)


@login_required
def RandomCodeGenerator(request,panel_number):

    chars =string.digits
    size = 8
    code=random_string_generator(size, chars)
    code_obj=SecretCode()
    code_obj.code=code
    code_obj.teacher_username=request.user.username
    panel=Panel.objects.get(panel_number=panel_number)
    code_obj.panel=panel
    code_obj.date_time_created=timezone.now()
    code_obj.save()
    context={
    'code':code,
    }
 


    # return HttpResponseRedirect(reverse("", kwargs={'pk': pk}))
    return render(request,'teacher/code.html',context)

def random_string_generator(str_size, allowed_chars):
    return ''.join(random.choice(allowed_chars) for x in range(str_size))



def Button(request):
    return render(request, 'teacher/button.html',{})


def PanelListView(request):
    list_of_panels=Panel.objects.all()
    context={
    'panel_list':list_of_panels,
    }
    return render(request,"teacher/panel_list.html",context)

teacher/templates/teacher/button.html
<!-- {% extends 'base_layout.html' %}


{% block content %}
{% if user.is_authenticated %}
<a href="{% url 'teacher:code' %}">generate code</a>

{% else %}
<h1>you need to log in</h1>
{% endif %}

{% endblock %} -->

teacher/templates/teacher/code.html
{% extends 'base_layout.html' %}


{% block content %}
{% if user.is_authenticated %}
<div class="alert alert-success">
  <strong>Success!</strong> todays code is:<div style="font-size: 30;">{{code}}</div>
</div>

{% else %}
<h1>you need to log in</h1>
{% endif %}

{% endblock %}

teacher/templates/teacher/index.html
{% extends 'base_layout.html' %}


{% block content %}
{% if user.is_authenticated %}
<h1>hello {{user.username}}</h1>
{% else %}
<h1>you need to log in</h1>
{% endif %}

{% endblock %}

teacher/templates/teacher/panel_list.html
{% extends 'base_layout.html' %}


{% block content %}
{% if user.is_authenticated %}
{% for i in panel_list %}
<ul type>
	<li>
		<a href="{% url 'teacher:requested' i.panel_number %}">
			Div:-{{i.panel_number}}
		
		</a>
	</li>
	
</ul>
{% endfor %}
{% else %}
<h1>you need to log in</h1>
{% endif %}

{% endblock %}

teacher/templates/teacher/profile.html
{% extends 'base_layout.html' %}


{% block content %}
{% if user.is_authenticated %}
<div class='container'>
<h1>   Name:-{{name}} </h1>
<h3>   Subject:-{{subject}}</h3>
 
 <a href="{% url 'teacher:requested' %} ">request code</a>

</div>

{% else %}
<h1>you need to log in</h1>
{% endif %}

{% endblock %}