Attendance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from accounts.views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/',auth_views.LoginView.as_view(template_name="registration/login.html"),name='login'),
    path('accounts/logout/',auth_views.LogoutView.as_view(template_name="registration/logout.html"),name='logout'),
  	path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
    path('home/', Home,name='home'),
]

student/urls.py
from django.urls import path
from .views import HomePageView,Profile,SubjectAttendance

app_name = 'student'


urlpatterns = [
	# path('', HomePageView,name='index'),
	path('profile/', Profile,name='profile'),
	path('attendance/',SubjectAttendance,name='attendance'),
	


]

templates/base_layout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Attendance Application</title>
  </head>
  <body>
      <div class="custom-padding">
        <nav>
            <div class="logo">Logo</div>

            <ul class="menu-area">
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'student:profile'  %}">Profile</a></li>
                  <li><a href="{% url 'logout' %}">logout</a></li>
                  <li><a href="{% url 'student:attendance' %}">give attendance</a></li>
                {% else %}
                  <li><a href="{% url 'login' %}">login</a></li>
                 {% endif %} 

            </ul>
        </nav>
    </div>

    {% block content %}
    {% endblock %}

  </body>
</html>